language: python
sudo: false
python:
  - "2.6"
  - "2.7"
install: 
  - 'pip install responses==0.5.0 pytest-pep8 pytest-cov'
  - 'python setup.py develop'
script: "py.test --pep8 --cov-report term-missing --cov internetarchive"
branches:
  only:
      - master  
