language: python
sudo: false
python:
  - "2.6"
  - "2.7"
install: 
  - 'pip install -e .'
  - 'pip install responses==0.5.0'
script: "python setup.py develop && py.test"
branches:
  only:
      - master  
