language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install: 
  - 'pip install -e . --use-mirrors'
  - 'pip install -e ".[speedups]" --use-mirrors'
script: "py.test"
branches:
  only:
      - master  
before_install:
  - sudo apt-get install python-dev libevent-dev
