language: python
sudo: false
python: "2.7"
install: 
  - pip install tox
env:
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py27
  - TOX_ENV=py26
script: 
  - tox -e $TOX_ENV
branches:
  only:
      - master  
